### ISSUE TITLE
Maven 3.0.2 build failed

### ISSUE THREAD

**Issue by essadek** [dgcloud/alfresco-share-site-logo-customization#8]
Using Eclipse Mars, when building the project I get an error related to file missing, I added

```
<relativePath>
        ../pom.xml
        </relativePath>
```

to both modules but still get the same error

```

[INFO] Scanning for projects...
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.leftxmas.alfresco:customise-site-logo-repo:3.0-SNAPSHOT (E:\HAYIL\DMS\Modules\alfresco-share-site-logo-customization-master\customise-site-logo-repo\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find org.alfresco.maven:alfresco-sdk-parent:pom:2.0.1-SNAPSHOT in https://artifacts.alfresco.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-public has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 12, column 10 -> [Help 2]
[ERROR]   
[ERROR]   The project com.leftxmas.alfresco:customise-site-logo-share:3.0-SNAPSHOT (E:\HAYIL\DMS\Modules\alfresco-share-site-logo-customization-master\customise-site-logo-share\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find org.alfresco.maven:alfresco-sdk-parent:pom:2.0.1-SNAPSHOT in https://artifacts.alfresco.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-public has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 12, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by essadek** [comment]
this the debug output 

```
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.alfresco.maven:alfresco-sdk-p
nt:pom:2.0.1-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:239)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:295)
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:155)
```

**Comment by essadek** [comment]
after adding this repo to maven, the error just vanish:

```
<repository>
    <id>oss-sonatype-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</repository>
```

**Comment by douglascrp** [comment]
@essadek Sorry about the late response, and thank you for taking the time to fix the issue.
I think the right thing to do would be to set the SDK version for a final version, available on maven central.
I'll do so when I have the opportunity.

May we close this issue?

**Comment by essadek** [comment]
Thanks @douglascrp for the feedback.
